# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineslots', '0002_funds_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='funds',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
