# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineslots', '0003_funds_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funds',
            name='amount',
            field=models.IntegerField(default=100),
        ),
    ]
